# -*- coding: utf-8 -*-
"""iris&breastcancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqySbihlDqHAvju3PHDhekH0qJL7m6QL
"""

# Decision Tree for Classification

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import (GaussianNB,MultinomialNB,BernoulliNB)
from sklearn.metrics import classification_report, confusion_matrix

# Dataset Preparation
a = input("please insert 1 for iris, 2 for Breast Cancer")
if(a=="1"):
    iris=load_iris()
    X=iris.data
    y=iris.target
    print(iris.feature_names)
    df= pd.DataFrame(X, columns=iris.feature_names)
    print(df.head())
else:
    breast_cancer=load_breast_cancer()
    X=breast_cancer.data
    y=breast_cancer.target
    print(breast_cancer.feature_names)
    df= pd.DataFrame(X, columns=breast_cancer.feature_names)
    print(df.head())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20
)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.tree import DecisionTreeClassifier

max_depths = [2, 10]
min_samples_splits = [2, 10]
min_samples_leafs = [2, 10]

results = []

for max_depth in max_depths:
  for min_samples_split in min_samples_splits:
    for min_samples_leaf in min_samples_leafs:
      for criterion in ['gini', 'entropy']:
        for splitter in ['best', 'random']:
          classifier = DecisionTreeClassifier(
            criterion=criterion,
            splitter=splitter,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf)
          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          report = classification_report(y_test, y_pred, output_dict=True)
          cm = confusion_matrix(y_test, y_pred)
          results.append({
            "max_depth": max_depth,
            "min_samples_split": min_samples_split,
            "min_samples_leaf": min_samples_leaf,
            "criterion": criterion,
            "splitter": splitter,
            "accuracy": report["accuracy"],
            "precision": report["macro avg"]["precision"],
            "recall": report["macro avg"]["recall"],
            "f1": report["macro avg"]["f1-score"],
            "confusion matrix": cm
          })
df = pd.DataFrame(results)
df

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))
if(a=="1"):
  plot_tree(
      classifier,
      feature_names=iris.feature_names,
      class_names=iris.target_names,
      filled=True
  )
else:
  plot_tree(
      classifier,
      feature_names=breast_cancer.feature_names,
      class_names=breast_cancer.target_names,
      filled=True
  )

plt.show()

smoothing_values = [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
results = []

for smoothing in smoothing_values:
    gnb=GaussianNB(var_smoothing = smoothing, priors=None)
    gnb.fit(X_train, y_train)
    y_pred = gnb.predict(X_test)
    # print(y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)
    results.append({
        "smoothing" : smoothing,
        "accuracy" : accuracy,
        "Precision": report["macro avg"]["precision"],
        "Recall": report["macro avg"]["recall"],
        "F1": report["macro avg"]["f1-score"],
        "confusion matrix" : cm
    })
df = pd.DataFrame(results)
df

# from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# scaler = MinMaxScaler()

# X_train_m = scaler.fit_transform(X_train)
# X_test_m = scaler.transform(X_test)
alpha_values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
results = []

for alpha in alpha_values:
    mnb = MultinomialNB(alpha=alpha, fit_prior=True)
    mnb.fit(X_train, y_train)
    y_pred = mnb.predict(X_test)
    # print(y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)
    results.append({
        "alpha" : alpha,
        "accuracy" : accuracy,
        "Precision": report["macro avg"]["precision"],
        "Recall": report["macro avg"]["recall"],
        "F1": report["macro avg"]["f1-score"],
        "confusion matrix" : cm
    })
df = pd.DataFrame(results)
df

"""BernoulliNB isn't looking at "petal length is 5.1" — it's basically asking "is petal length greater than 0?"
"""

from sklearn.naive_bayes import BernoulliNB

thresholds = np.median(X_train, axis=0)

X_binary_train = (X_train > thresholds).astype(int)
X_binary_test = (X_test > thresholds).astype(int)

alpha_values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
results = []

for alpha in alpha_values:
    bnb = BernoulliNB(alpha=alpha, fit_prior=True)
    bnb.fit(X_binary_train, y_train)
    y_pred = mnb.predict(X_binary_test)
    # print(y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)
    results.append({
        "alpha" : alpha,
        "accuracy" : accuracy,
        "Precision": report["macro avg"]["precision"],
        "Recall": report["macro avg"]["recall"],
        "F1": report["macro avg"]["f1-score"],
        "confusion matrix" : cm
    })
df = pd.DataFrame(results)
df